# Site settings
title: Nazel Video Downloader
description: A free Video download manager
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nazel Video Downloader
user_description: Nazel Video Downloader is GUI front-end client for the popular CLI application Youtube-dl. NVD is cross-platform, so it can run on Windows, Linux and MacOS . It is free (for freedom and no cost), open source and available for development and maintenance by the community. NVD is written in Java and the JavaFX toolkit.
user_title: A free, open source, cross-platform video download manager based on youtube-dl
email: gs_elzoughby@yahoo.com
twitter_username: nazel
github_username:  elzoughby
gplus_username:  nazel

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
