# Site settings
title: Nazel Video Downloader
description: A free Video download manager
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Nazel Video Downloader
user_description: Nazel Video Downloader is GUI client for the popular CLI application Youtube-dl. It has the features you need in a video downloader application and supports a very long list of video and audio streaming websites. Nazel is free, <br> cross-platform and open source application written in Java and the JavaFX toolkit.

user_title: A free, cross-platform video download manager
email: gs_elzoughby@yahoo.com
github_username: elzoughby
repository_name: Nazel
# Google-analytics
google-analytics:
  id: "UA-85733887-2"

exclude: ['package.json', 'src' , 'node_modules']
